-- PROCEDIMENTO PARA CRIAR UM USUÁRIO P/ ACESSAR O BD
CREATE LOGIN alunoFS13
WITH PASSWORD = 'alpha-zulu';

-- ATRIBUINDO O PERFIL DO LOGIN ALUNO P/ O USUÁRIO
CREATE USER alunoFS13 FOR LOGIN alunoFS13;

-- CONCEDENDO PERMISSÃO APENAS PARA OS COMANDOS DE "SELECT" E "INSERT"
GRANT SELECT TO alunoFS13;
GRANT INSERT TO alunoFS13;